[package]
name = "fa_tool"
version = "0.1.7"
edition = "2021"

[dependencies]
clap = "4.4.3"
serde = "1.0.188"
walkdir = "2.4.0"
yeslogic-fontconfig-sys = { git = "https://github.com/Vernoxvernax/fontconfig-rs.git" }
